### ISSUE TITLE
UI overflow bug found on Registration

### ISSUE THREAD

**Issue by ghost** [chakrakan/fitcon#15]
![image](https://user-images.githubusercontent.com/57729525/76349542-95952f80-62e0-11ea-92c8-ad23b36dddf2.png)

**Comment by chakrakan** [comment]
I think this, and #16 is due to the different type of emulators we are using and the different resolution of the phone used for the emulation

My code was tested on 
- Pixel 3 Android emulator
- iPhone 11 Pro Max emulator 

I had no issues with the iPhone emulator, but also had slight overflow seen in #1 

I don't know if we can normalize the layout for all different phone sizes but we can try. Also, we should probably just cater requirements to the latest devices given those are the ones more being used right now.

**Comment by ghost** [comment]
I have tested it on Google pixel phone. 
This phone has an issue of overflowing so I have managed to put "Flexible" widget to solve the issue
